import = ["/home/matthew/.config/alacritty/dracula.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
#family = "DejaVuSansMNerdFont"
style = "Bold"

[font.bold_italic]
#family = "DejaVuSansMNerdFont"
style = "Bold Italic"

[font.italic]
#family = "DejaVuSansMNerdFont"
style = "Italic"

[font.normal]
#family = "DejaVuSansMNerdFont"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
